---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: airflow-fernet-key
  namespace: airflow
spec:
  encryptedData:
    fernet-key: AgDAvcRMoZz1XwAmGkj1yE3l49XqqJr3Ae385v3mWjD99o1VIRI4u++hZ3xrKHn/4z/8X/Bx8qL7thHZbkxMK+MX5ngAFcbwv4f1ZjWz54MPUYRGpgCHUUuVbOHd5vHOx9qW7JBP5DrMJVQigft6kxgYxI5WUtuZddKd6q/BOhExW/nBygslPVUwcKXQ5TfWPyXqUIK0EJS813SkYqxIYt2WCpPuG/Fkhy/dkHCI2DTPIKLLhWUIVuR1mW0lgc407nQBDYfbg++g1DoarpR9WXWn6ezLht8gK5WDJ5Tymdq4LqLj7GQYrICJ2OcEED7AcdPYoJfMdaYP0ghMoUDghJMa/hlGoL7z7d0TJf+Fll45fBi8aDvC/4IvyUCvYW/IH5huF2fhdyPxHqYhBYWrFgG43k+tmcsEDYizCaQm8uuiXYPe6WPfhCVal0mKuMZRKsAE3Howetzs0yEiNdxrB0+ve4c9QTyo+XBC87xSC2TslDoTwieA2+7R5V44qXVbcWCsCsLcglijuevfJWueYkK3W68M8WA7X+jIT9E6pzSosiuD6WFSY3oAT07Krwgu960cjCsSZ50Ab+V7BHYHGoD9Dh5i1kWPwQCncV+IQBbJezKZz7fdHgS33VmUUAjolBjSVDdwWH/YKsQJiBP+OgkPUoYbhNqtINPN8BJVx9MYgELGzzPfJxAXD3O78nzKwbn5mi3iNOdPhdvSaOU3etulp4zHfmiZ3unTzZblq4lXHg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: airflow-fernet-key
      namespace: airflow
    type: Opaque
