---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: airflow-image-pull-secret
  namespace: airflow
spec:
  encryptedData:
    .dockerconfigjson: AgDBxmLO6KwcBfS+5rLfc4Co/X/D/WfmGl6V6e1NnaHCh+o5Mo8qVlHlxziPWu5xIHcchw7p/A/56cvqVP7BJ9HDn+oxlaHHJapuKwIY+WE3Hm/tUgWHX57ufBAjLKlcCY6Q2hTQyz6nkb86owmcMXCIrDK38oK0Zrr7RUJz163oRLyVHj3q/DApg924h5ZHA+65rN78q9XXf+naLQtML7NE/6TEaFmvjlHNibynlm0XGJGD8M4ILH59ytV8OuQDPB+7dy271OHVouH8W8MbvZS3EvfWomfkRTVRCRAdRJsqiRFbVddN7lexH3lMq8bjv/oL4IOffIYIgjxp+SZU9m6IDWUnJ3E78CCSk9ZjxzOuFsCl+V0Z56KQEF1lEbNCVYcxWaJWoLqu6yCG2UsLgbcgnO0lAkIfXG4/w1Aj99ZdftgV9wrUNZ6EccmxDpELI0VaB4mSPTL70vHJNYmpEtlTtnjyzuC5cT0/4cLRmMkED2KG0jVJCH8c9ssOLw3bCB2pDueQFu7Mflkmu8jijy24EXpTron8EsYrFfnukYvskjt5J/LEyR2I9/QvjPuxf5zVuh5UW4m/Zbk4jZ4ZyycM7c98C1y+caQt45XvukfkyKRCr/JASTC6l68Vz5WKM3poimEoq1IyddnU0GTMZkZDgezWb+oSd/9GnMI/XqAdAXPJottv5+woRdcNW12iB6HCBx+c5iRsjTu05H7SJYfwUsgMTD6o0ZICCEqnjF3Nmscbv0S8D2crn4HGZxibv8OAGqgBq96Cy+frnILbK9tpJ0pn9XTh9nBRN92ifIQCgTJL/ZNsrwzG+ajzZVoGqwJbcAQLaAlt4V+i2J8zFCJpGAiWVmf/sqLrgs0n+heMykg8VebdhHlJWoXsbJd9Lpr3p7AGQSOHbqyieXtCBUN05lNoLhZ3vJyYBH8v+bLVNqnIguq2PjEgVi8siTAa5UHZQUHNUFJhsRqkdLHFmf1mFyBW4A7Td3jye0rTSo/iFkGiiTcG30oAMQ1AWbUEo257LYLfdXc8ibgRV056m/InATXRGSj/WHPWy1/Qtvaaow==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: airflow-image-pull-secret
      namespace: airflow
    type: kubernetes.io/dockerconfigjson
