---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: airflow-webserver-key
  namespace: airflow
spec:
  encryptedData:
    webserver-key: AgAp5Iwu711r03kXcqTmpllQEq/RtfOYX8TEi+zntSdqSsuwMHUHFNOktLoYVstsQGJr86+vPM9J9OMCIxu8OVCmnqSgI1lvd7prGBMFFniQClSs93W7JBjLw4O7DWHUECiXn4ltnyNXl+Bl52P3BQyhSVUdpVi1X6z/8UOZt/RYXbndyGK3BDiRYH30lTCG5D//OnFZuVftIS04W011i0NHiSCRJ5agk1JRXg8lBWPFaXxrB0f0G9Ya01Hso3ak8vDeDNMJf60qZOlwJEzpn0oEL0VWikosyw3+YNcpUcWe70yXww5xO4H7xWeq6EQBIaRBT9j3oWhpVQkrDVn52fa1pi2zrOs1rb5TOCrBLUXDwKGXbsY37SUfvqiuIDDMqAgXKAa5PbZRZ4+6qPjJfdDDsUNvOvF7vrpB1oPnnuK7GguvKXltjKYMPlu7gW83FfdnV5KhIZVLGcm6ZFMjL78VAdSHbAh0tNf0NBZD0Mc+2o4VZ2z0YxKgbbGwq4V+tcBRTKlApgpNB6rJkJdsnCg5A73mF06FdS3GllYwxk5bSaxVEt3sCITJZGkN8Y1YRSAs59nkEopm/33D10J7Yqi2DNms6jtC9eDWSDVAdxOd9OhT0AvGRa10gUTpYADCqutp8eFBKXPeLcvAa29kOeKZ52Met2ZeGWk2PzGtOs4MntO8W52HXDK/wnEAM11+3rCOZkbeWmgDM0+j0Io40tU/
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: airflow-webserver-key
      namespace: airflow
    type: Opaque
