---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cnpg-cluster-superuser-auth-secret
  namespace: airflow
spec:
  encryptedData:
    password: AgC95KVhTQfbppuZa+tulBUFNE3pPIkLs4/HQ6bFCtz1g6Uknl3WZkZeXMItT8eUzFYJ45wzV3LV+VIAi7XHBA4W3zGY58GpT9g3C+NmbBgyzVbxANRtbX80/fGDAiyKg+Kt1wlzrERmPs2LJK5kb6JCM5tgtPhRlBBvtEYnJzheGLLkxOoIIDWB0ut/nOWeT9CAWV6zSm3fLV69XvoSBzBm7ZmUYb6VogCF6aO1vx/pMyqltsNaeACxn9cTxZ0N5fI1BvaR7FRoIppTxqg0sXgqOTUKVvevG7RsrIe8LBr8wZEFCPNGE4RAXgCsrck4SuCcwnHObctKxqiFbu/9rm/++cfZzZYJbaGNuvSSYrRk2rnf8ctGoQktY0hQXJgq1CPhROuwoka1/qieEk49jQa/ao/f3aIdcRksAQGa72RxdjY1QSzS3elr5x25xrr25KuyyUgld8iviFGH/CcBtCA6J7bKM/OXJcCOat7bOgWvNt37/hNLU3uasSbvqbfUD1+v4cl+twhsiK9FcZ/ACxK72aztgTG3QJXFR9MeoX9nt6OoozrKLHhuCFcO+sdohvLDueR7icPX6dw8lVW/kkiOp1H5IKVMw/i6m2UPhFqYSA0pG8XTDY2tV/m0HziVBuRMoD2++rnyise1F8G96frS1DouZBFji+mYlTY11mYKFyr3MZPaKxH88oc3cwyNchHob5E69j3glnxiyAq+3xV/Sz83Y1wI18g=
    username: AgCosVWMKD3fWNQjev2YO6PABgRe9gUd7jJ6+8mgT6J1F+rF7X/V+v49bhdCXFXkR5s9nk1YBFpjmclX2lB+kbd1cILwOcqQXH2D88X6fpQhOjzfCKsrtb5EVqa/q+nm4cllZtkTXJZXSPEP3uK3R4I5iD29i8qoyGTJxV9w5BXQ0zDMdA15pow5nf6p2agI7YERxDbyBvXrXLMfz5OZXUIVTe2H9KutqwpDsjlV6kfCIpFJfMy3WaFidjpLOh76mzXJMF3G9PBtlxRc/S846Sf464RYRxdNq5qd1qdE3FjNXo3hvdnYvUpQjBYb5LKrIWe1ilms3qiC+3mj7lImL9J0tVBVHsaoAvyqVegTGYwuYlWi5YCRxkDbnr+tMuZaHfPNJHQNMH/xPBCn+C3mSsOup5hf9fs29IH6S4hzjvfDYBNLWs626R+Q3kcjl10C+PBlTRaa546AK72twnGY1X4Qjxzs5LxAb3AQNCtHk6ltT8qb5Ichz1KCiuKxdKc0yS6LGgKJsK+ZZrYZ/WQjPbudk5hZzdzfKrfejYyqlckJLbx8mg9mAb0IMPkIvBJzm31h01RdRgNeh2ELkJHhSfDT8uXK//vcVphqgszGds4/qa/jfs7BtnPy0a+Z4Ltr5s7XgRfE/wn+Ail4xyoK3Dw+v0zJSqWR2x2inSobsYOxbVkxNwyHQP1BtV7ijoIpVWWHzEHD960RVA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cnpg-cluster-superuser-auth-secret
      namespace: airflow
    type: kubernetes.io/basic-auth
