---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cnpg-database-user-auth-secret
  namespace: airflow
spec:
  encryptedData:
    password: AgBb2/IQ+8C1fmFP+pXQfwetbBiodNq/sTrXWQE+yVGdN4uJ9cge5BTLYE0lnip/X9H/vGyqQv78qph/+5Ikv5UV6OAnE3pguxcxBZaC4CRwft8cLDh44DNLH0wmSkDRiTXdFzZZCvK1Wng2w8TTrbcNWdGanGc6cH/t3NRWraWS6L5BWqlICgUkuoIWaJ+dEZ9bn02qprvU5fVIgLbGk7jSTrH5IRe34QriC0cBvpa1EApsjrgyJhUkzA0G5uCO6dMYA7TZnoA3Zdmhl9d/zh/S1S75iuEcQqdUSkNqtmDE/RKaiCDM97NV4UZ+2ELZOqRZTY+Sm5PTWQJZk12564E/rUa6o/d+Wt2InSb0mXnDgNEUQMALYEuzqayZEB5xS++t7SsyLu2ok2J5gOpfNW2Ee41BCr6ptilB1CsN3Gs5T9RC/7FS9kropq5j5wit3nTOvGksOO/fcFhC1TDdVy6FHv5o8eJBQmcm0HrBdWvVkjsbGJGq/OKodeHtlWt2k7NemsfgvdjgFjbjPZQlC2Tw2m1XCV9b7k31ve8/Ni1mI0Ecq9KRlEnwPAAzDkKP/RcxOQERf3UWcHpEhi67VQBGnNAD4L93X4Wq173Fq8h9SCe5ownYee3FcZqUVmbt+x/YLWQlofaTcAvDQQZ0kTjP5HYVnc11K6mp94WKzFYCnxbL4gMT9NaUxV3RozssryZdiZKb0sqsVy9Iv+Q=
    username: AgAKYX+XVpBlcaBsQjenHFci4C0KyTJi0hR+fgZ8MHzjKFOCHPq3gizJq5cHYX7zHRwYhMLXH2UfapTBUnD+71mBTyaUIlF/uKtsPUJdNxCiPg9aMpU+itjibHOBG8NGXI6e9XNGi+F8pwdhPe2QmCFYN1GCOn3xcG2qctVIreENTH3ZToUirT7ISptdNpSBfgSnSxJbW0wMu9IYr+lOw4PWs/uwdlixSED8NOKlS90ik26QN9UtapZdbed0tDNea/yTyw+3a+ZmVwj7Z+I1ZqANcO1oDG8fJobi+vEBN1STeLR57qYouvK8tekbxu62MRmcj4nHWw9FLsJOmd6iRWrVbYZZ7JLl6QIeKUm02j8xsHIyEg2T5jNAkDyp7ONkROT/lXH/z0atIkadO0/vTPBP6rNdk/zhHqii4S9OnCjF85SxwKdia4wfaYlD6FW7pTQBdw7crGPMNBgaV0Oy9JrtCFPF1gjzd883eKaAZ14fMxo8tVOUN/YBZ1dcPNfO7x1bZsI10U1jx8WlJqyyOdFxR9IyLspDcKR02RQwHg7jTLxYNb8KVO9dfQk/mFLVKHjmzn7/UUFlfaVMVNe9RaOkH7DfyRaP0hWJby5pGytWKiwEyPbiz5pM9At+X8/nHU5tfjAccdDWRgBdUPuuAXmInzlGBzEPt96UntdScvmXAA870VA9vmtnglwOStOj7zX/yMJbP/xf
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cnpg-database-user-auth-secret
      namespace: airflow
    type: kubernetes.io/basic-auth
