---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: external-dns
  namespace: external-dns
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgCRS/p8JVufiE87nc2yG0XphfRV/d0XcdNs3uuMnOKrZyMkACjPQLi0hRX1chZe9JgI7oJMJxnwQ4FC6mwL+QWoX6liGj/oyZvW0/hYHwn/gDL3xKT3Xy90QFBAE6mh83BhVJd0D7QNLJ1/zZXrNzXBph7QvIXQ0fDSsbby5rCzsIYWDLXlNtbBVhtoL+nrPjFZSMiTj1dw3AZDuY52ZHjs0Jge7q4I3uG5Q5VelAMfYrSOrt9yWDjgQj7qrr1PCMwFpRvZD1C/JrH+EvL/4QaMl3Sbe6Y5EdL6hwwixdRiCtQySnUft6igBVGUXIQAEfWK7euApSfMwbCJxVWvwjRBLxaRJH5QQFQ2zWVx870ey0QIpKAcAKKuXtcOu901eMoU55/tPXpoouIHGn9vBL1WGn3hTAFsaCzzG2SrT1PqnAuPKr0gr0aRf33qhB2bwAYtdgIjfb03PrSoHcauzfqWA+KFMqB2OCsGLoUoaXyErdj5lg6XWI1kBXRXwu2n84skFN/38WIF2w6Hl2PbPGjMXeJTo5ErkRm/Uaf6kIwTUtzoaOV4KRMso0rbog/ypb4vjcEMXu+ZNV5Ai24q/eBjsdWBrXWSDnBGp9s72e2lpnG/UjPqm+Z14jQjSg9yyCeN20AHgV7/yNohA/j6p70HYvQw6vafNpD1qfY5fyXGEwblbtmyjXY+6a0rB6/U1gvEA+xjpB2cg/S3+qw87LNsSK91Og==
    AWS_SECRET_ACCESS_KEY: AgBqNrpMFBvJaag4BNoxgesL8mgJyG4kAUhUMwe8PfXpBBTuQUHAOCPxaBq3i+6m1nRIU/5tYQws++RedLAu1o06aD5KCRP+pd2zhO8+AYuCiyLfi1ZGybQDhTWGEHfBkgd2QLQkBKwIvX75AFlMxuTQHLQ2DmmxlsQXUdOAGhGEviIV92KMDNQl5lEEgwehT5J98issIsUnVDtVqAFMujbbtJo7YXprL6tBco4ih9DWN1Ey0XzRjeMi/ZgfarYJ7+YxnGBXXUbW28ZuL//h11BnCA8rFOplLMauGKfZjr5rnRVl/TwtiJea1BxNXH3o/nGMqIYc5Dqg7SU2TDSm55WBXl+UauPqNObbtsqctyw3b3GK3cvEdpu+/virK8wWTG5COCISYhxmA8Z34bFJ9N6wftB6vIjNUHV11RPTqXVhBWVhCbZeeRDroy36vtTaZ12fRRCDDyr/YJOsoGvsrVnfOOSkWYdgEtyMqQCzmNTToi94x3WDLEez8H8ZzOfkxEY+RIho9H9AmUWnaZkkaLAdTPfuqtpcE/sc6bJvwhqTK7ylbcbNsDGzcU750FfPqrENAP50X4wj2u+NL8WsnQbjfA2G3EZgKlc7vlECH8FfYF4cBjZYcy/UCGUVjAcc7WGwtfGeP6Mq45wtEJGk+ag0Gfi9OjyfoPr6hl9xoU3JCFoLJhfQT294975Iujjl31M4sapXlvbk+BkwdRSCvAqW4BmKG4UIcB8E15MqGu3QJP06XMBMTU/j
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: external-dns
      namespace: external-dns
