---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: airflow-git-credentials
  namespace: airflow
spec:
  encryptedData:
    GIT_SYNC_PASSWORD: AgBLzPZhA/RyihOvPKeMPP8tuIurRPM8K7xEn2ov7OBgGGnOIepxWPCQsBMtIMc0obJhduVY9iDyD1TkscTdul4B0JFPHJU4t3zrmJ68yydtPpmsZ+lzbJxZJQIGKD9p3kMhCLGZ843oR/8qDAWrww1Fi27Wf8lzZvLdCn7APJ7Egz84L9xdkUzx6IFqMVk4uivYtfK1KtkJD6vOwqJFYs4vkcvnJn7yczrD2wReSR0HsssvYhVySVmuTHHFkn97OMIT/cvIngvVqVZK7RtospR5raxx9nVYCtxHYhjmhUYkVKKKk85BISD1wdHPBfO4+sMIeY6kWGWRdNYvY7Bfs1NoRpWXw8vkmPJJWP5b/9nJUCdcKsEPcNgI/2jNi5SOx0LhK+45f4KQlsrvChzTiVIHvQAwpbMESx5WZX5ZzgBb3HFnMHybhBpj9k/FyYFD+z6eqHI63LyTsqG0bt9odfZSHLgbh7WeE1K2vijVF//2ffRdylM/ndf1v6Eb9WfuXeR5Hps5/eHSozadL9C9k+/USOndFNEbk97DJ2GwRa9oS4f47Qekv7omjcsI463klx1mWsdr2roIHMOx2T1B95jvchbXNtjFOQloG8VuH7dHMVZu/Y6NL9jn80uNenQc+j84p0rfTRS09Ps8raWdeqJEwajD4m8Yoi0ll3Ox9yrKqCJPPGGlXqrOBHznSefkOEfOn7YY64fj44OXzng5I1sdjUufWp4JX3tyAJ6r67e25Wjdpa2s65mZ
    GIT_SYNC_USERNAME: AgCdTU/8QokrmkpkALy6i8k21nv7OR4avGnxnTJx0IK1htF6CjLlvrmA/KFJc+YKGovabsz20nQRaQmX9Qzc6XUzSBhfjc8wPsrHrIEykkU04GETQJBqEuBxoI2Zj8dyln81pryMc3YF5UENn5YZb9ltHdmE0Cxo5z/Jkx8Xf5FZm5C84K4u9cd4/YXvp3gtxD4P4DhmR3tvXs/bPLPEUBnU4xTc4paTG0ZxJzLWnGpqgjMNqPZXg/biNwfwxRa9FwWJusZMQcLQVUXNzngXxV3X29QTyd/RPZMr1wKgiPygUktnxb6shpdyVXWIZ1VPfr/BDjfcf/fXSyCEoOkmTmn9W2rXcQkEtl8nl94vxYDCYzPpd4tomPouEIZQiOOqu6edSIElii+37gztZTyM4RoEMmdq0UubfzBdb5xI4CpoCbSfm5gv0e8HPlgBFMAoth+M82tSLVjVIIM9pkupVMOaw0n9Yp1D+2hJdgN2qBtTMAq0E9rlTh2L25Eq2e0eJ8qgK0mZ7IZMbRXeSd7y4hr32s2R8ebNwY8RyBmzWP3d4nCWDf0+8k2/jixcY0V2Qlz5SGLeeCApnoiM0PcWevPGb1phHPzD8R1NswqIiz62kt9csO82ctMvXHjtUMVbqcp7HvqNtHbNifJqOSZ0VpdhNen9fMaFiui5NZqPDNWiK66ZxB5cMz/8GAppcACOcJdvFaPSDgcA4JiGB8M=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: airflow-git-credentials
      namespace: airflow
