---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: postgresql-connection-string-secret
  namespace: airflow
spec:
  encryptedData:
    connection: AgBCFbROWNjz1GA2CYfmvO4fD/9eKQhxkDIWf7QaIy0UkgtENkk2ydLXc0qw4o2HggxrNVC1Ky+uXytJ7+8c14V2Gb1qXoSXJTaHtSD3Y2jAV+6UiRCb2/ZonT6nz7Pm5a6cJ6c22+4KsyyAqL1po/zL+r7FAz6VHL+N9WEnsLvR5pujzx/2KDoQPB2E3O58qaGJk29p6oiu5nKjrkOqIgzwp1pXk3LaT/FhiwQYmUzP5FyjYTzwMHql1IklfX73RECh/RMvaFJF5oayP5yvdoZJKwWQQ/GaUTrAlFpr59h42kfrbpKMVxxzCoD9pPj4bH9auAsayKT93TeylXtz6FywMK549MdBDMDVgW4hRie/NpF2iQOWld3uqVMl6Y4x7dTXCzT2Lr8opX+6y9qKCMkTyX6bPOVYx5o0o9JC+u0nQYuiJhlAHPkuInbbVE70/K8jXetKieeeGKEI4aMZMe5Vkk+PQHXpCbgHVG9ErMlJ/VtoUqjjuF2iRqdf5aBovwUpY6+8CgBB0Z/ojN4BcxxZ8Ie5w1gLULcjxh2uuiZpAW1mAlvZ+xixrAKGBG46/E7oNB9GiBScb5qDwV77XlC91OY/ZrU6Rs1C5se36MYxyxF5EY1oIzmqKpBJ9ZtEywpAMpy7fp5Y/327PGMHs9QDoQuQgLLDbDzkQtBBLwsjNVdVMENmmyXgcLbluCphBoSOnmEw6LSWkLdj52kKe8SmpzlZAX70fltqNOkaAdQjtQwxtEckOvRUzkZ4VTlIyG3nbQuPgpkW8fUzlpkW6WqvuCZnNNn3gZUp
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: postgresql-connection-string-secret
      namespace: airflow
    type: Opaque
